In [1]:
from sklearn.datasets import load_iris

iris = load_iris()

X = iris.data
y = iris.target


In [2]:
print X.shape
print y.shape

(150, 4)
(150,)


In [3]:
from sklearn.neighbors import KNeighborsClassifier

In [4]:
knn = KNeighborsClassifier(n_neighbors=1)

In [5]:
print knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


In [6]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

In [7]:
knn.predict([3, 5, 4, 2])

/home/miti/.local/lib/python2.7/site-packages/sklearn/utils/validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

In [8]:
X_new = [[3,5,4,2], [5,4,3,2]]
knn.predict(X_new)

array([2, 1])

In [14]:
knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X, y)

y_pred = knn.predict(X_new)
print metrics.accuracy_score(y, y_pred)

ValueError: Found input variables with inconsistent numbers of samples: [150, 2]

In [10]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression()

logreg.fit(X, y)

logreg.predict(X_new)

array([2, 0])

In [12]:
y_pred = logreg.predict(X)
print len(y_pred)
print y_pred

150
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 2 1 1 1
 1 1 1 1 1 1 1 1 1 2 2 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [13]:
from sklearn import metrics
print metrics.accuracy_score(y, y_pred)

0.96
